# Generated by Django 3.1.5 on 2021-03-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('amount_sale', models.FloatField(default=0)),
                ('amount_recieved', models.FloatField(default=0)),
                ('amount_changed', models.FloatField(default=0)),
                ('employee', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('qty', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'transactiondetail',
                'verbose_name_plural': 'transactiondetails',
            },
        ),
    ]
