# Generated by Django 3.1.5 on 2021-03-08 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20210308_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='transaction',
            field=models.ForeignKey(db_column='pk', default='', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='sales.transaction'),
        ),
    ]
