# Generated by Django 3.1.5 on 2021-02-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_encoded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
