# Generated by Django 3.1.5 on 2021-02-15 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210215_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='encoded_by',
        ),
    ]
